import assert from 'node:assert/strict';
import { act } from 'react';
import { createRoot } from 'react-dom/client';
import TopicStack from '../src/TopicStack';
import { obsidianCardHandlers } from '../src/obsidian-card';
import { sendCardToSide, returnCardFromSide } from '../src/card-flight';

const tick = () => new Promise(resolve => setTimeout(resolve, 0));
const animations = [];
Element.prototype.animate = function (_frames, options) {
  let resolve, reject;
  const finished = new Promise((yes, no) => { resolve = yes; reject = no; });
  finished.catch(() => {});
  const animation = { element:this, options, finished, playState:'running', cancel() { this.playState='idle'; reject(new Error('cancelled')); }, finish() { this.playState='finished'; resolve(); }, pause() { this.playState='paused'; }, reverse() { this.playState='running'; } };
  animations.push(animation); return animation;
};
Element.prototype.getAnimations = function ({ subtree = false } = {}) { return animations.filter(animation => animation.playState !== 'idle' && (animation.element === this || subtree && this.contains(animation.element))); };
HTMLElement.prototype.getBoundingClientRect = () => ({ left:0, top:0, right:200, bottom:300, width:200, height:300 });
const motionListeners = new Set();
const media = { matches:false, addEventListener(_name, callback) { motionListeners.add(callback); }, removeEventListener(_name, callback) { motionListeners.delete(callback); } };
window.matchMedia = () => media;
const setReduced = value => { media.matches = value; motionListeners.forEach(callback => callback()); };
let frameId = 0;
const frames = new Map();
globalThis.requestAnimationFrame = window.requestAnimationFrame = callback => { frames.set(++frameId, callback); return frameId; };
globalThis.cancelAnimationFrame = window.cancelAnimationFrame = id => frames.delete(id);
const flushFrames = () => { const pending = [...frames.values()]; frames.clear(); pending.forEach(callback => callback(performance.now())); };
globalThis.CSS = { escape:value => value };

const root = createRoot(document.getElementById('root'));
const posts = Array.from({length:20}, (_,index) => ({postKey:`post-${index}`,account:'fixture',shortcode:String(index),likes:20-index,timestamp:index+1}));
const renderStack = () => <TopicStack posts={posts} renderCard={(post, expand) => <button className="fixture-card" onClick={expand}>{post.postKey}</button>} />;
const click = async selector => { await act(async () => { document.querySelector(selector).click(); await tick(); }); };
try {
  document.documentElement.dataset.effects = 'immersive';
  await act(async () => root.render(renderStack()));
  await click('.post-stack-trigger');
  assert.equal(document.querySelectorAll('.post-stack-modal .fixture-card').length,20);
  assert.ok(animations.every(animation => animation.options.duration + animation.options.delay <= 760), 'A large deck has a bounded entrance');
  await click('[aria-label="Close stack"]');
  const exits = animations.filter(animation => animation.playState === 'running');
  assert.ok(exits.every(animation => animation.options.duration + animation.options.delay <= 780), 'A large deck has a bounded return');
  await act(async () => { root.render(null); await tick(); });
  await act(async () => root.render(renderStack()));
  await click('.post-stack-trigger');
  const count = animations.length;
  await act(async () => { await tick(); });
  assert.ok(document.querySelector('.post-stack-modal'), 'Cancelled close must not close a later stack');
  assert.equal(animations.length,count,'Cancelled close must not start a stale settling animation');
  await act(async () => { document.documentElement.dataset.effects='off'; await tick(); });
  assert.ok(document.querySelector('.post-stack-grid'), 'The open stack stays present while preferences stop its motion');
  assert.ok([...document.querySelector('.post-stack-grid').children].every(card => !card.inert));
  assert.equal(document.querySelector('.post-stack-modal').hasAttribute('data-dealing'),false);
  await click('[aria-label="Close stack"]');
  assert.equal(document.querySelector('.post-stack-modal'),null);
  document.documentElement.dataset.effects='immersive';
  await click('.post-stack-trigger');
  await act(async () => { setReduced(true); await tick(); });
  assert.ok(document.querySelector('.post-stack-grid'), 'The open stack stays present while preferences stop its motion');
  assert.ok([...document.querySelector('.post-stack-grid').children].every(card => !card.inert));
  await click('[aria-label="Close stack"]');
  assert.equal(document.querySelector('.post-stack-modal'),null);
  await act(async () => root.unmount());
  setReduced(false);

  const card = document.createElement('article');
  card.innerHTML='<div class="media"></div><button>Action</button>';
  document.body.append(card);
  let reads = 0;
  card.getBoundingClientRect = () => { reads++; return {left:0,top:0,width:200,height:300}; };
  for (let index=0;index<15;index++) obsidianCardHandlers.onPointerMove({currentTarget:card,target:card.firstChild,clientX:100+index,clientY:180,pointerType:'mouse'});
  assert.equal(reads,0); flushFrames(); assert.equal(reads,1,'Pointer bursts share one layout read');
  assert.ok(card.style.transform);
  obsidianCardHandlers.onPointerMove({currentTarget:card,target:card.lastChild,clientX:100,clientY:180,pointerType:'mouse'});
  assert.equal(card.style.transform,'','Moving onto an action clears the previous tilt');
  obsidianCardHandlers.onPointerMove({currentTarget:card,target:card.firstChild,clientX:120,clientY:180,pointerType:'mouse'});
  document.documentElement.dataset.effects='off'; await tick(); flushFrames();
  assert.equal(card.style.transform,'','Turning effects off cancels pending tilt');
  card.remove(); document.documentElement.dataset.effects='immersive';

  const backdrop = document.createElement('div'); backdrop.className='sidebar-backdrop';
  const inspector = document.createElement('aside'); inspector.className='obs-preview-side';
  const slot = document.createElement('div'); slot.dataset.obsSideview='next'; inspector.append(slot);
  const source = document.createElement('article'); source.style.cssText='width:200px;height:300px';
  document.body.append(backdrop,inspector,source);
  let staleClose = 0;
  returnCardFromSide('old',()=>{staleClose++;});
  sendCardToSide(source,'next'); flushFrames();
  assert.ok(document.querySelector('.obs-persistent-card'));
  await new Promise(resolve=>setTimeout(resolve,400));
  assert.equal(staleClose,0,'A replaced fallback close must not close a new selection');
  document.documentElement.dataset.effects='off'; await tick();
  assert.equal(inspector.dataset.obsPhase,'ready','Effects off lands the current card immediately');
  assert.equal(document.querySelector('.obs-persistent-card').parentElement,slot);
  let closed = false;
  returnCardFromSide('next',()=>{closed=true;});
  assert.equal(closed,true); assert.equal(document.querySelector('.obs-persistent-card'),null);
  assert.equal(source.classList.contains('obs-in-transit'),false);
  backdrop.remove(); inspector.remove(); source.remove();
  console.log('PASS motion: bounded large stacks, cancelled close/reopen, dynamic reduced/off, RAF tilt and stale-flight cleanup');
  process.exit(0);
} catch (error) { console.error(error.message); process.exit(1); }
