import React, { act } from 'react';
import { createRoot } from 'react-dom/client';
import TopicStack from '../src/TopicStack';
import ProductHome from '../src/ProductHome';
import ProductHeader from '../src/ProductHeader';
import { PrefsProvider } from '../src/prefsContext';
const email = 'designer@example.com';
const task = { id: 7, designerEmail: email, title: 'My assigned story', status: 'in_progress', recommendedAccounts: ['chatgptricks'], productionPoints: 3, scheduledDate: '2026-09-05', scheduledStartMinutes: 100 };
const data = { viewer: { email, displayName: 'Designer' }, assignedRequests: [task, { ...task, id: 8, title: 'Another designer story', designerEmail: 'other@example.com' }], planningRequests: [task], requests: [{ status: 'pool' }], pendingTicketCount: 2 };
globalThis.fetch = window.fetch = async () => ({ ok: true, status: 200, json: async () => data });
const el = document.body.appendChild(document.createElement('div')); const root = createRoot(el);
try {
  await act(async () => { root.render(<PrefsProvider><ProductHeader current="home" /><ProductHome email={email} coordinator={false} /></PrefsProvider>); await new Promise((r) => setTimeout(r, 50)); });
  await act(async () => { await new Promise((r) => setTimeout(r, 50)); });
  if (!el.textContent.includes('My assigned story') || el.textContent.includes('Another designer story')) throw new Error('Personal home must scope work to the viewer');
  if (el.querySelector('.product-nav a[href="/tracker.html"]')) throw new Error('Designer must not see Tracker');
  if (!el.querySelector('.home-task[href*="r="]')) throw new Error('Next action needs a deep link');
  await act(async () => { root.render(<PrefsProvider><ProductHeader current="home" coordinator /><ProductHome email={email} coordinator /></PrefsProvider>); });
  await act(async () => { await new Promise((r) => setTimeout(r, 50)); });
  if (!el.querySelector('.product-nav a[href="/tracker.html"]') || !el.querySelector('a[href="/queue.html?inbox=1"]')) throw new Error('Coordinator navigation and inbox missing');
  let chosen = null;
  const variants = [{postKey:'a',likes:12},{postKey:'b',likes:97},{postKey:'c',likes:30}];
  await act(async () => root.render(<TopicStack posts={variants} renderCard={(post, expand) => <button className="test-card" onClick={expand || (() => { chosen = post.postKey; })}>{post.postKey}</button>} />));
  if (el.querySelectorAll('.test-card').length !== 1 || el.querySelector('.test-card').textContent !== 'b') throw new Error('Stack must show most liked cover only');
  await act(async () => el.querySelector('.test-card').click());
  if ([...el.querySelectorAll('.post-stack-modal .test-card')].map((x) => x.textContent).join(',') !== 'b,c,a') throw new Error('Expand must expose every version in likes order');
  await act(async () => el.querySelectorAll('.post-stack-modal .test-card')[1].click());
  if (chosen !== 'c') throw new Error('Expanded version must be selectable');
  await act(async () => el.querySelector('.post-stack-heading button').click());
  if (el.querySelectorAll('.test-card').length !== 1) throw new Error('Collapse must restore stack');
  console.log('PASS stack cover, expansion, choosing an alternate and collapse');
  await act(async () => { root.unmount(); });
  console.log('PASS role-based Home, task deep links, personal scope and coordinator inbox');
  process.exit(0);
} catch (error) { console.error(error.message); process.exit(1); }
