// Product UI copy. Preserve source content and stable API field names.
export const PRODUCT_ES = {
  "Quick add": "Agregar rápido",
  "New post, fading over its first {hours} hours -- about {left} left": "Post nuevo, se atenúa durante sus primeras {hours} horas; quedan aproximadamente {left}",
  "Already up to date": "Ya está actualizado",
  "Cover refreshed": "Portada actualizada",
  "Last 24 hours": "Últimas 24 horas",
  "Last 3 days": "Últimos 3 días",
  "Last 7 days": "Últimos 7 días",
  "Last 30 days": "Últimos 30 días",
  "AI & Automation": "IA y automatización",
  "Technology & Science": "Tecnología y ciencia",
  "Business & Entrepreneurship": "Negocios y emprendimiento",
  "Lifestyle & Community": "Estilo de vida y comunidad",
  "News & Entertainment": "Noticias y entretenimiento",
  "Personal Brand": "Marca personal",
  "Sentient home": "Inicio de Sentient",
  "Sentient tools": "Herramientas de Sentient",
  "free": "libres",
  "ON": "Activo",
  "OFF": "Inactivo",
  "Review saved.": "Revisión guardada.",
  "Corrections saved.": "Correcciones guardadas.",
  "JEV assessment updated.": "Evaluación JEV actualizada.",
  "Review saved. You have reached the end of this view.": "Revisión guardada. Llegaste al final de esta vista.",
  "JEV assessment updated. Compare it with the source evidence before saving your review.": "Evaluación JEV actualizada. Compárala con la evidencia de origen antes de guardar la revisión.",
  "Review brief copied.": "Brief de revisión copiado.",
  "Could not copy the brief.": "No se pudo copiar el brief.",
  "Could not open that post. Your current review is still here.": "No se pudo abrir ese post. Tu revisión actual se conserva.",
  "The review could not be saved. Your corrections are still here. Try again.": "No se pudo guardar la revisión. Tus correcciones se conservan. Inténtalo de nuevo.",
  "JEV could not complete this review. Try again.": "JEV no pudo completar esta revisión. Inténtalo de nuevo.",
  "Your account does not have Promos access.": "Tu cuenta no tiene acceso a Promos.",
  "The request timed out. Refresh before retrying an action; it may have completed.": "La solicitud tardó demasiado. Actualiza antes de repetir la acción; puede que se haya completado.",
  "Slack did not confirm delivery.": "Slack no confirmó el envío.",
  "Active 7d": "Activos en 7 días",
  "No data": "Sin datos",
  "unassigned": "sin asignar",
  "events ·": "eventos ·",
  "posts ·": "posts ·",
  "Disclosure language": "Declaración comercial",
  "Brand relationship": "Relación con la marca",
  "Affiliate or referral offer": "Oferta de afiliación o referidos",
  "Call to action": "Llamada a la acción",
  "Commercial language": "Lenguaje comercial",
  "Hashtag signal": "Señal de hashtag",
  "Related-post support": "Apoyo de posts relacionados",
  "Possible missed promotion": "Posible promoción no detectada",
  "Conflicting evidence": "Evidencia contradictoria",
  "Needs human review": "Necesita revisión humana",
  "No promotion signal found": "No se encontraron señales de promoción",
  "Assessment available": "Evaluación disponible",
  "Source not recorded": "Fuente no registrada",
  "Unclassified": "Sin clasificar",
  "Caption": "Texto de la publicación",
  "First comment": "Primer comentario",
  "Partnership metadata": "Metadatos de colaboración",
  "Image alt text": "Texto alternativo de la imagen",
  "Transcript": "Transcripción",
  "Cover text": "Texto de portada",
  "Requested JEV review": "Revisión JEV solicitada",
  "Connections": "Conexiones",
  "Manage your workspace": "Administra tu espacio de trabajo",
  "Connect your AI tools": "Conecta tus herramientas de IA",
  "Connect websites and apps": "Conecta sitios web y aplicaciones",
  "Access unavailable": "Acceso no disponible",
  "Active 30d": "Activos en 30 días",
  "7d": "7 días",
  "Events": "Eventos",
  "Groups": "Grupos",
  "days": "días",
  "snapshots": "registros",
  "OCR indexed": "OCR indexados",
  "OCR remaining": "OCR pendientes",
  "Slack alert channel": "Canal de alertas de Slack",
  "Slack webhook": "Webhook de Slack",
  "Queue DMs": "Mensajes de Queue",
  "closed": "cerrados",
  "active": "activos",
  "Grouping similar posts…": "Agrupando posts similares…",
  "Load more posts": "Cargar más posts",
  "loaded": "cargados",
  "JEV candidate": "Candidato JEV",
  "JEV checked": "Revisado por JEV",
  "new": "nuevo",
  "reviewed": "revisado",
  "dismissed": "descartado",
  "Keyword": "Palabra clave",
  "Code": "Código",
  "Detected": "Detectado",
  "Review {brand} on @{account}": "Revisar {brand} en @{account}",
  "Review promotion on @{account}": "Revisar promoción en @{account}",
  "Post by @{account}": "Post de @{account}",
  "Open original post by @{account}": "Abrir post original de @{account}",
  " · More available": " · Hay más resultados",
  " · Private": " · Privada",
  "\"Suggested\" is the account's average first-hour likes (the same number the HOT check itself compares against), rounded up to the nearest hundred.": "«Sugerido» es el promedio de likes de la cuenta en la primera hora, que también usa la evaluación HOT, redondeado a la siguiente centena.",
  "% used --": "% usado —",
  "+ likes/hr": "+ likes/h",
  ". This choice is also used by future automatic refreshes.": ". Esta selección también se usa en las actualizaciones automáticas futuras.",
  "/7 strong signals · confidence": "/7 señales fuertes · confianza",
  "100 posts": "100 posts",
  "500 posts": "500 posts",
  "2,000 posts": "2.000 posts",
  "@username": "@usuario",
  "A promotion signal alone does not confirm payment.": "Una señal de promoción por sí sola no confirma un pago.",
  "A shared brand or topic helps comparison; it does not establish a paid campaign.": "Una marca o tema en común ayuda a comparar, pero no confirma una campaña pagada.",
  "ADMIN": "ADMIN",
  "API connections": "Conexiones API",
  "Agent connections": "Conexiones de agentes",
  "Account group": "Grupo de cuentas",
  "Account group unavailable": "Grupo de cuentas no disponible",
  "Account onboarding": "Incorporación de cuentas",
  "Account · loaded": "Cuenta · cargada",
  "Account:": "Cuenta:",
  "Active": "Activa",
  "Active role": "Rol activo",
  "Active, 30d": "Activos, 30d",
  "Active, 7d": "Activos, 7d",
  "Add account sends a request to Dev. Only Dev can add new accounts.": "Agregar cuenta envía una solicitud a Dev. Solo Dev puede agregar cuentas nuevas.",
  "Add an Instagram account to your workspace.": "Agrega una cuenta de Instagram a tu espacio de trabajo.",
  "Added": "Agregado",
  "Admin access": "Acceso de administrador",
  "Admin or Dev access required": "Se requiere acceso Admin o Dev",
  "Admin panel requests": "Solicitudes del panel de administración",
  "Admins and Devs manage shared access here. Every listed person has Dashboard and Post Designer access; the Queue role below grants an additional operating perspective when needed.": "Admins y Devs administran aquí el acceso compartido. Todas las personas de la lista tienen acceso al Dashboard y a Post Designer; el rol de Queue añade una perspectiva operativa cuando se necesita.",
  "All changes saved": "Todos los cambios guardados",
  "All classifications": "Todas las clasificaciones",
  "All matching stacks loaded": "Todos los grupos coincidentes cargados",
  "All reviews": "Todas las revisiones",
  "All selected content": "Todo el contenido seleccionado",
  "Assessment source": "Fuente de la evaluación",
  "Attachment preview": "Vista previa del adjunto",
  "Automatic browser zone": "Zona automática del navegador",
  "Automation keyword": "Palabra clave de automatización",
  "Back": "Volver",
  "Back to Dashboard": "Volver al Dashboard",
  "Brand, account, keyword or evidence…": "Marca, cuenta, palabra clave o evidencia…",
  "Brief or note": "Brief o nota",
  "Canonical": "Canónica",
  "Caption unavailable in this stored record.": "El texto de la publicación no está disponible en este registro.",
  "Catch up missing posts": "Recuperar posts faltantes",
  "Catch up posts": "Recuperar posts",
  "Catching up…": "Recuperando…",
  "Category": "Categoría",
  "Change image": "Cambiar imagen",
  "Change the review status or scan stored posts to look for promotion signals.": "Cambia el estado de revisión o analiza los posts guardados para buscar señales de promoción.",
  "Checking account access…": "Verificando acceso de la cuenta…",
  "Checking workspace access…": "Verificando acceso al espacio de trabajo…",
  "Checking…": "Verificando…",
  "Classification": "Clasificación",
  "Classification clear": "Clasificación clara",
  "Classification includes a saved human correction.": "La clasificación incluye una corrección humana guardada.",
  "Click a row to edit its label, category, subcategory, tool visibility, HOT threshold, or avatar, or pull more history.": "Haz clic en una fila para editar su nombre, categoría, subcategoría, visibilidad, umbral HOT o avatar, o importar más historial.",
  "Client / brand": "Cliente / marca",
  "Client unknown": "Cliente desconocido",
  "Close Jev tools": "Cerrar herramientas Jev",
  "Close admin options": "Cerrar opciones de administración",
  "Close assignment dialog": "Cerrar diálogo de asignación",
  "Close promotion review": "Cerrar revisión de promoción",
  "Close selected post details": "Cerrar detalles del post seleccionado",
  "Colombia (UTC−5)": "Colombia (UTC−5)",
  "Costa Rica (UTC−6)": "Costa Rica (UTC−6)",
  "Commercial intent support": "Respaldo de intención comercial",
  "Commercial link found": "Enlace comercial encontrado",
  "Compare related signals": "Comparar señales relacionadas",
  "Comparing similar posts…": "Comparando posts similares…",
  "Complete": "Completado",
  "Confirm": "Confirmar",
  "Confirm delete": "Confirmar eliminación",
  "Confirming with server…": "Confirmando con el servidor…",
  "Confirming…": "Confirmando…",
  "Conflicting signals": "Señales contradictorias",
  "Content count": "Cantidad de contenido",
  "Content to scrape": "Contenido que se extraerá",
  "Copy review brief": "Copiar brief de revisión",
  "Copy the saved assessment, source evidence and related context. Unsaved corrections are not included.": "Copia la evaluación guardada, la evidencia y el contexto relacionado. Las correcciones sin guardar no se incluyen.",
  "Correct the assessment using the evidence. Review status is tracked separately.": "Corrige la evaluación con la evidencia. El estado de revisión se registra por separado.",
  "Couldn't find that account -- double-check the handle.": "No se encontró esa cuenta. Revisa el usuario.",
  "Couldn't load usage data.": "No se pudieron cargar los datos de uso.",
  "Create a custom list": "Crear una lista personalizada",
  "Creating…": "Creando…",
  "Current classification": "Clasificación actual",
  "Daily activity per person": "Actividad diaria por persona",
  "Dash": "Dash",
  "Dashboard requests": "Solicitudes del Dashboard",
  "Date from": "Fecha inicial",
  "Date range": "Rango de fechas",
  "Date to": "Fecha final",
  "Deactivate": "Desactivar",
  "Default": "Predeterminado",
  "Defaults to the handle": "Se usa el usuario de forma predeterminada",
  "Delete account": "Eliminar cuenta",
  "Delete list": "Eliminar lista",
  "Delete “": "¿Eliminar «",
  "Deleted from Instagram": "Eliminado de Instagram",
  "Deleting…": "Eliminando…",
  "Details": "Detalles",
  "Detection evidence": "Evidencia de detección",
  "Detection tools": "Herramientas de detección",
  "Dev · full access": "Dev · acceso completo",
  "Discard": "Descartar",
  "Discard changes & continue": "Descartar cambios y continuar",
  "Discard unsaved corrections?": "¿Descartar las correcciones sin guardar?",
  "Discovered through JEV review of stored posts.": "Detectado mediante una revisión JEV de los posts guardados.",
  "Dismiss & next": "Descartar y continuar",
  "Dismissed": "Descartado",
  "Display label (optional)": "Nombre visible (opcional)",
  "Download PDF": "Descargar PDF",
  "Draft kept": "Borrador conservado",
  "ENG": "EN",
  "ES": "ES",
  "Each badge shows identity, roles, and managed accounts. Open the gear to edit. Changes are only marked saved after the server confirms them.": "Cada tarjeta muestra la identidad, los roles y las cuentas administradas. Abre el engranaje para editar. Los cambios se marcan como guardados después de la confirmación del servidor.",
  "Edit list": "Editar lista",
  "Exact excerpt found in the caption above.": "Fragmento exacto encontrado en el texto de arriba.",
  "Extra notes": "Notas adicionales",
  "Extract": "Extraer",
  "Extract history": "Extraer historial",
  "Extracted brand candidates": "Marcas candidatas extraídas",
  "Failed": "Falló",
  "Files": "Archivos",
  "Filter promotion reviews": "Filtrar revisiones de promociones",
  "Find missed promos with JEV": "Buscar promociones omitidas con JEV",
  "Flagged by stored-post detection rules.": "Marcado por las reglas de detección de posts guardados.",
  "Full caption": "Texto completo de la publicación",
  "Generate a client-ready PDF with public account highlights and top posts": "Generar un PDF para clientes con datos públicos y posts destacados de la cuenta",
  "Generate a client-ready media kit with public account highlights, overall performance, and standout posts.": "Genera un media kit para clientes con datos públicos, rendimiento general y posts destacados de la cuenta.",
  "Golden nugget": "Idea destacada",
  "Golden nugget candidate": "Candidato a idea destacada",
  "Group last 72 hours": "Agrupar últimas 72 horas",
  "Group recent posts": "Agrupar posts recientes",
  "Grouping similar posts… You can keep using Research.": "Agrupando posts similares… Puedes seguir usando Research.",
  "Grouping…": "Agrupando…",
  "HOT /hr": "HOT /h",
  "HOT threshold (likes in the first hour)": "Umbral HOT (likes en la primera hora)",
  "Hide this status; the import continues on the server": "Ocultar este estado; la importación continúa en el servidor",
  "Highlighted text is an exact match to stored caption evidence.": "El texto resaltado coincide exactamente con la evidencia guardada.",
  "History to import": "Historial que se importará",
  "How many of the most recent items": "Cuántos de los elementos más recientes",
  "How many posts to pull (default 2000)": "Cantidad de posts que se importarán (por defecto 2000)",
  "Human review": "Revisión humana",
  "Human review recommended": "Se recomienda revisión humana",
  "Imports up to the most recent 2,000 items per selected source. Use a date range or a count for a narrower, faster import.": "Importa hasta los 2.000 elementos más recientes por fuente seleccionada. Usa fechas o una cantidad para acotar y acelerar la importación.",
  "In progress": "En curso",
  "Inactive": "Inactiva",
  "Indirect evidence": "Evidencia indirecta",
  "Initial history import": "Importación inicial del historial",
  "Insights requests": "Solicitudes de Insights",
  "Instagram handle": "Usuario de Instagram",
  "Instagram post": "Post de Instagram",
  "Instagram username": "Usuario de Instagram",
  "JEV assessment": "Evaluación JEV",
  "Jev developer tools": "Herramientas Jev para desarrollo",
  "Jev research query": "Consulta de investigación Jev",
  "Jev tools": "Herramientas Jev",
  "Keep editing": "Seguir editando",
  "Keep list": "Conservar lista",
  "Label": "Nombre visible",
  "Leads default to Promos only. Competitors default to both tools.": "Los leads se muestran por defecto solo en Promos. Los competidores, en ambas herramientas.",
  "Limit": "Límite",
  "Limit / source": "Límite / fuente",
  "Load": "Cargar",
  "Loaded posts only": "Solo posts cargados",
  "Loading": "Cargando",
  "Loading Promos…": "Cargando Promos…",
  "Loading full post evidence…": "Cargando toda la evidencia del post…",
  "Loading more…": "Cargando más…",
  "Loading promotion signals…": "Cargando señales de promoción…",
  "Loading…": "Cargando…",
  "MB (": "MB (",
  "MB /": "MB /",
  "MB free)": "MB libres)",
  "Manage user": "Administrar usuario",
  "Managed Queue accounts": "Cuentas administradas de Queue",
  "Mark reviewed & next": "Marcar como revisado y continuar",
  "Maximum posts": "Máximo de posts",
  "Media kit": "Media kit",
  "Minutes per PP": "Minutos por PP",
  "Missing brand": "Marca faltante",
  "Multiple brand candidates": "Varias marcas candidatas",
  "Name": "Nombre",
  "Needs classification": "Necesita clasificación",
  "Needs review": "Necesita revisión",
  "New": "Nuevo",
  "New accounts stay here while their history is collected. This status survives a reload and clears after the import finishes.": "Las cuentas nuevas aparecen aquí mientras se recopila su historial. El estado se conserva al recargar y se retira cuando termina la importación.",
  "New data is incoming": "Están llegando datos nuevos",
  "New list": "Lista nueva",
  "Newest first. The limit applies to each selected source; choosing Both can run one Posts import and one Reels import.": "Los más recientes primero. El límite se aplica por fuente; elegir Ambas puede iniciar una importación de Posts y otra de Reels.",
  "Newest post": "Post más reciente",
  "Next": "Siguiente",
  "Next signal": "Señal siguiente",
  "No JEV assessment yet. The action above runs one for this post.": "Todavía no hay evaluación JEV. La acción de arriba ejecuta una para este post.",
  "No JEV check": "Sin revisión JEV",
  "No Queue needed": "No necesita Queue",
  "No Slack webhook configured on the server.": "No hay un webhook de Slack configurado en el servidor.",
  "No accounts": "Sin cuentas",
  "No accounts match “": "Ninguna cuenta coincide con «",
  "No accounts match.": "Ninguna cuenta coincide.",
  "No context excerpt was saved with this assessment.": "No se guardó un fragmento de contexto con esta evaluación.",
  "No designer activity yet.": "Todavía no hay actividad de diseño.",
  "No excerpt stored.": "No hay fragmentos guardados.",
  "No loaded posts match these filters.": "Ningún post cargado coincide con estos filtros.",
  "No managed Queue accounts": "Sin cuentas administradas de Queue",
  "No one loaded yet.": "Todavía no se cargaron personas.",
  "No posts in this review queue.": "No hay posts en esta cola de revisión.",
  "No related signals in the loaded results.": "No hay señales relacionadas en los resultados cargados.",
  "No rule evidence excerpts were stored. Review the caption and available JEV context.": "No se guardaron fragmentos de evidencia de reglas. Revisa el texto y el contexto JEV disponible.",
  "No runs found.": "No se encontraron ejecuciones.",
  "No tool visibility": "Sin visibilidad en herramientas",
  "No valid web links stored.": "No hay enlaces web válidos guardados.",
  "None stored": "Ninguno guardado",
  "Not a priority yet": "Todavía no es una prioridad",
  "Not available": "No disponible",
  "Not confirmed · draft kept": "Sin confirmar · borrador conservado",
  "Not found verbatim in this caption. Check the original post.": "No aparece literalmente en este texto. Revisa el post original.",
  "Not identified": "Sin identificar",
  "Not linked": "Sin vincular",
  "Not reviewed": "Sin revisar",
  "Notes": "Notas",
  "Nothing assigned right now.": "No hay nada asignado ahora.",
  "Nothing hidden yet": "Todavía no hay nada oculto",
  "Nothing is hot right now.": "No hay posts HOT ahora.",
  "Offer details": "Detalles de la oferta",
  "Older posts that went hot before the last": "Posts anteriores que fueron HOT antes de las últimas",
  "Oldest post": "Post más antiguo",
  "Oldest post:": "Post más antiguo:",
  "One link per line": "Un enlace por línea",
  "Only Sentient administrators and developers can open this workspace.": "Solo los administradores y desarrolladores de Sentient pueden abrir este espacio de trabajo.",
  "Only visible at DEV level": "Visible solo para DEV",
  "Only visible to User 03.": "Visible solo para User 03.",
  "Open in Queue": "Abrir en Queue",
  "Open original post": "Abrir post original",
  "Opening review…": "Abriendo revisión…",
  "Opening…": "Abriendo…",
  "Optional context": "Contexto opcional",
  "Optional: only posts from this date on": "Opcional: solo posts desde esta fecha",
  "Original": "Original",
  "Other": "Otro",
  "Other stored evidence": "Otra evidencia guardada",
  "Ours": "Nuestras",
  "Outside current filtered view": "Fuera de la vista filtrada actual",
  "PP ·": "PP ·",
  "Paid partnership and promotion signals": "Señales de colaboración pagada y promoción",
  "Per-person detail": "Detalle por persona",
  "Points to check": "Puntos por verificar",
  "Post": "Post",
  "Post Designer": "Post Designer",
  "Post Designer only": "Solo Post Designer",
  "Post history import runs in the background after this -- you can keep using the dashboard while it works.": "Después de este paso, el historial se importa en segundo plano. Puedes seguir usando el dashboard mientras se ejecuta.",
  "Post menu": "Menú del post",
  "Post preview unavailable": "Vista previa del post no disponible",
  "Press Enter to check the account, or just continue.": "Pulsa Enter para verificar la cuenta o continúa.",
  "Previous signal": "Señal anterior",
  "Product": "Producto",
  "Product not identified": "Producto sin identificar",
  "Product unknown": "Producto desconocido",
  "Production points": "Puntos de producción",
  "Promising": "Prometedor",
  "Promising idea": "Idea prometedora",
  "Promos": "Promos",
  "Promotion code": "Código de promoción",
  "Promotion review": "Revisión de promoción",
  "Promotion review results": "Resultados de revisión de promociones",
  "Published date of the oldest post we have on file for this account": "Fecha de publicación del post más antiguo guardado de esta cuenta",
  "Queue recommended": "Se recomienda Queue",
  "Queues a durable seven-day full-library recovery across active accounts, including the dedicated Reels source. It keeps running even when this page is closed or refreshed.": "Programa la recuperación de siete días de la biblioteca completa de cuentas activas, incluida la fuente Reels. Sigue ejecutándose si cierras o recargas esta página.",
  "Quick add to Pool": "Agregar rápido al Pool",
  "Quick add to Pool with defaults": "Agregar rápido al Pool con valores predeterminados",
  "ROLE": "ROL",
  "Reactivate": "Reactivar",
  "Rebuilds stacks for posts published during the last 72 hours using the time-weighted similarity rules.": "Reagrupa los posts publicados en las últimas 72 horas con reglas de similitud ponderadas por tiempo.",
  "Reconnect to this scan": "Reconectar con este análisis",
  "Recover all accounts": "Recuperar todas las cuentas",
  "Recovering…": "Recuperando…",
  "Reference links": "Enlaces de referencia",
  "Refresh avatar": "Actualizar avatar",
  "Regular": "Normal",
  "Related loaded signals": "Señales relacionadas cargadas",
  "Related posts": "Posts relacionados",
  "Relationship reading": "Lectura de la relación",
  "Reload queue": "Recargar cola",
  "Reloading...": "Recargando…",
  "Remove": "Quitar",
  "Remove attached image": "Quitar imagen adjunta",
  "Remove image": "Quitar imagen",
  "Remove this account from Accounts while preserving its post history.": "Quita esta cuenta de Cuentas y conserva su historial de posts.",
  "Requests, 30d": "Solicitudes, 30d",
  "Research": "Research",
  "Research query…": "Consulta de investigación…",
  "Reset filters": "Restablecer filtros",
  "Restore to new": "Volver a nuevo",
  "Restoring…": "Restaurando…",
  "Restricted workspace": "Espacio de trabajo restringido",
  "Retry access check": "Verificar acceso de nuevo",
  "Retry now": "Reintentar ahora",
  "Retry save": "Reintentar guardado",
  "Review": "Revisar",
  "Review @": "Revisar @",
  "Review actions save your corrections. Dismissal alone does not change the classification.": "Las acciones de revisión guardan tus correcciones. Descartar por sí solo no cambia la clasificación.",
  "Review brief": "Brief de revisión",
  "Review corrections": "Correcciones de revisión",
  "Review focus": "Enfoque de revisión",
  "Review navigation": "Navegación de revisión",
  "Review next": "Revisar siguiente",
  "Review priority": "Prioridad de revisión",
  "Review promotion signals, check the evidence, and improve detection together.": "Revisa las señales de promoción, verifica la evidencia y mejora la detección con el equipo.",
  "Review status": "Estado de revisión",
  "Review with JEV": "Revisar con JEV",
  "Reviewed": "Revisado",
  "Reviewing with JEV…": "Revisando con JEV…",
  "Role preview": "Vista previa del rol",
  "Rule scan": "Análisis con reglas",
  "Rule scans analyze the last 30 days of stored competitor posts. JEV discovery checks stored candidates using AI. Existing human corrections are kept.": "Las reglas analizan los posts de competidores guardados de los últimos 30 días. JEV revisa los candidatos con IA. Las correcciones humanas existentes se conservan.",
  "Rules result at JEV review": "Resultado de reglas al revisar con JEV",
  "Run OCR sweep": "Ejecutar barrido OCR",
  "Run a semantic review only when you need another reading of the stored context.": "Ejecuta una revisión semántica cuando necesites otra lectura del contexto guardado.",
  "Runs the engagement cycle for every account. Normally happens on its own every 30 minutes.": "Ejecuta el ciclo de engagement de cada cuenta. Normalmente se realiza automáticamente cada 30 minutos.",
  "Sales": "Ventas",
  "Same data Queue's own Admin overlay used to show in a second, separate panel -- one Reports tab here instead of two admin tools telling the same story.": "Los datos de administración de Queue se centralizan aquí en la pestaña Reportes.",
  "Same topic": "Mismo tema",
  "Save": "Guardar",
  "Save changes": "Guardar cambios",
  "Save corrections": "Guardar correcciones",
  "Save list": "Guardar lista",
  "Saving...": "Guardando…",
  "Scan stored posts and find missed signals": "Analizar posts guardados y buscar señales omitidas",
  "Scan with rules": "Analizar con reglas",
  "Scraping": "Extrayendo",
  "Search by handle, label, category, or subcategory…": "Buscar por usuario, nombre, categoría o subcategoría…",
  "Search loaded posts": "Buscar posts cargados",
  "Search people or roles…": "Buscar personas o roles…",
  "Search users by name, email, or role": "Buscar personas por nombre, correo o rol",
  "Selected post details": "Detalles del post seleccionado",
  "Semantic promo:": "Promoción semántica:",
  "Semantic support measures commercial intent in the available text. It is not a payment probability. The historical rules result may differ from the current classification.": "El respaldo semántico mide la intención comercial del texto disponible. No es una probabilidad de pago. El resultado histórico de las reglas puede diferir de la clasificación actual.",
  "Send a one-off Slack message for anything that doesn't fit HOT posts, disk, or snapshot alerts.": "Envía un mensaje puntual de Slack para avisos distintos de posts HOT, disco o capturas.",
  "Send alert": "Enviar alerta",
  "Send to Pool": "Enviar al Pool",
  "Settings command center": "Centro de ajustes",
  "Show historical HOT posts": "Mostrar posts HOT históricos",
  "Show posts with at least this many comments": "Mostrar posts con al menos esta cantidad de comentarios",
  "Show posts with at least this many likes": "Mostrar posts con al menos esta cantidad de likes",
  "Show the posts you have hidden, so you can bring them back": "Mostrar los posts ocultos para poder restaurarlos",
  "Showing saved values": "Mostrando valores guardados",
  "Sign in to continue": "Inicia sesión para continuar",
  "Slack ID": "ID de Slack",
  "Sort by": "Ordenar por",
  "Stack menu": "Menú del grupo",
  "Status": "Estado",
  "Status unavailable": "Estado no disponible",
  "Stored assessment": "Evaluación guardada",
  "Stored context evidence; not highlighted as caption text.": "Evidencia de contexto guardada; no se resalta como texto de la publicación.",
  "Stored signal": "Señal guardada",
  "Strongest:": "Más fuerte:",
  "Subcategory": "Subcategoría",
  "Suggest post": "Sugerir post",
  "Suggested:": "Sugerido:",
  "Switch among your assigned roles.": "Cambia entre los roles que tienes asignados.",
  "Tagged": "Etiquetado",
  "Tags": "Etiquetas",
  "The canonical account cannot be deactivated.": "La cuenta canónica no se puede desactivar.",
  "This Google account": "Esta cuenta de Google",
  "Time zone": "Zona horaria",
  "Title (optional)": "Título (opcional)",
  "Trainee": "Aprendiz",
  "Try again": "Reintentar",
  "Try another focus or search, or load more posts.": "Prueba otro enfoque o búsqueda, o carga más posts.",
  "U0123456789": "U0123456789",
  "Unclear relationship": "Relación poco clara",
  "Unsaved changes": "Cambios sin guardar",
  "Unsaved corrections": "Correcciones sin guardar",
  "Unscheduled": "Sin programar",
  "Upload image": "Subir imagen",
  "Urgency": "Urgencia",
  "Urgent": "Urgente",
  "Use 1–30 letters, numbers, periods, or underscores. Invalid handles are rejected before any Apify lookup.": "Usa de 1 a 30 letras, números, puntos o guiones bajos. Los usuarios inválidos se rechazan antes de consultar Apify.",
  "Use my default role": "Usar mi rol predeterminado",
  "Verify these names before correcting the client.": "Verifica estos nombres antes de corregir el cliente.",
  "View details": "Ver detalles",
  "Viral Coordinator": "Coordinador viral",
  "Visible in tools": "Visible en herramientas",
  "What do you want to notify? (You can paste an image here too)": "¿Qué quieres notificar? También puedes pegar una imagen aquí.",
  "What should this person do with this post?": "¿Qué debe hacer esta persona con este post?",
  "When the team is online (UTC)": "Cuándo está conectado el equipo (UTC)",
  "Who actually opens sentientdash.app, how often, and when — last": "Quién abre sentientdash.app, con qué frecuencia y cuándo — últimos",
  "You can add another account while an import is running; the server queues it automatically.": "Puedes agregar otra cuenta durante una importación; el servidor la pone en cola automáticamente.",
  "Your classification, client or product edits have not been saved.": "Los cambios de clasificación, cliente o producto no se han guardado.",
  "across everyone": "entre todas las personas",
  "active days": "días activos",
  "active ·": "activos ·",
  "can use the regular Sentient tools, but cannot manage shared settings.": "puede usar las herramientas habituales de Sentient, pero no administrar ajustes compartidos.",
  "closed ·": "cerrados ·",
  "days.": "días.",
  "e.g. AI news, Spanish, Competitors to watch": "p. ej., Noticias de IA, Español, Competidores a seguir",
  "e.g. User 03": "p. ej., User 03",
  "e.g. natgeo": "p. ej., natgeo",
  "h.": "h.",
  "handle": "usuario",
  "isn’t authorized for sentientdash.app. Ask for access, then sign in again.": "no está autorizada en sentientdash.app. Solicita acceso y vuelve a iniciar sesión.",
  "last 7d": "últimos 7d",
  "loaded posts": "posts cargados",
  "loaded signals": "señales cargadas",
  "loaded · Grouped automatically by topic or brand": "cargados · Agrupados automáticamente por tema o marca",
  "members checked": "miembros verificados",
  "more": "más",
  "more stacks": "grupos más",
  "name@example.com": "nombre@ejemplo.com",
  "never signed in": "nunca inició sesión",
  "none": "ninguno",
  "normal": "normal",
  "optional": "opcional",
  "optional · up to 20 MB each": "opcional · hasta 20 MB por archivo",
  "people": "personas",
  "possible outliers": "posibles casos atípicos",
  "post": "post",
  "posts in": "posts en",
  "relevant results": "resultados relevantes",
  "requests ·": "solicitudes ·",
  "required": "obligatorio",
  "stacks": "grupos",
  "stacks · showing": "grupos · mostrando",
  "stored signals": "señales guardadas",
  "total": "total",
  "unknown account": "cuenta desconocida",
  "urgent": "urgente",
  "· Costa Rica time": "· hora de Costa Rica",
  "· HOT at": "· HOT a las",
  "· Published": "· Publicado",
  "· score": "· puntuación",
  "”? The accounts and their posts will be kept.": "»? Las cuentas y sus posts se conservarán.",
  "⌘K": "⌘K",
  "Reconnecting to the shared Post DB…": "Reconectando con la base de posts compartida…",
  "The workspace connection timed out. Please try again.": "La conexión con tu espacio de trabajo tardó demasiado. Inténtalo de nuevo.",
  "We could not connect to your workspace. Check your connection and try again.": "No se pudo conectar con tu espacio de trabajo. Revisa tu conexión e inténtalo de nuevo.",
  "Could not sign out. Check your connection and try again.": "No se pudo cerrar sesión. Revisa tu conexión e inténtalo de nuevo.",
  "avg": "prom.",
  "Story": "Historia",
  "green": "verde",
  "lime": "amarillo neón",
  "blue": "azul",
  "coral": "coral"
};
