// Interface copy for copied review briefs. Source evidence and JEV guidance
// are deliberately excluded from translation.
export const PROMO_BRIEF_ES = Object.freeze({
  'PROMOS REVIEW BRIEF': 'BRIEF DE REVISIÓN DE PROMOCIONES',
  'Brand': 'Marca', 'Product': 'Producto', 'Account': 'Cuenta', 'Post': 'Publicación',
  'Published': 'Publicado', 'Classification': 'Clasificación', 'Unknown client': 'Cliente desconocido',
  'Not specified': 'Sin especificar', 'unknown': 'desconocida', 'Link unavailable': 'Enlace no disponible',
  'Date unavailable': 'Fecha no disponible', 'Review status': 'Estado de revisión',
  'Review priority': 'Prioridad de revisión', 'high': 'alta', 'normal': 'normal', 'low': 'baja',
  'new': 'nuevo', 'reviewed': 'revisado', 'dismissed': 'descartado',
  'triage only; not a probability': 'solo priorización; no es una probabilidad',
  'REVIEW CHECKS': 'PUNTOS DE REVISIÓN',
  'JEV and label disagree': 'JEV y la etiqueta no coinciden',
  'The saved semantic assessment reads this differently from the current promotion label. Compare both with the original post.': 'La evaluación semántica guardada interpreta esto de forma distinta a la etiqueta actual de promoción. Compara ambas con la publicación original.',
  'Denial in the evidence': 'Negación en la evidencia',
  'A denial of sponsorship appears alongside a promotion label. Check its context and any separate affiliate offer.': 'Aparece una negación de patrocinio junto a una etiqueta de promoción. Revisa su contexto y cualquier oferta de afiliación independiente.',
  'Classification needs review': 'La clasificación necesita revisión',
  'The available detection has not established a clear promotion classification.': 'La detección disponible no ha establecido una clasificación de promoción clara.',
  'JEV discovery candidate': 'Candidato descubierto por JEV',
  'Semantic discovery surfaced this post for human review; it does not establish a paid relationship.': 'La búsqueda semántica encontró esta publicación para revisión humana; no establece una relación pagada.',
  'JEV requests review': 'JEV solicita revisión',
  'The saved assessment reports ambiguity in the available post context.': 'La evaluación guardada indica ambigüedad en el contexto disponible de la publicación.',
  'Brand not identified': 'Marca no identificada',
  'Identify the promoted brand from the source if it is present; leave it unknown otherwise.': 'Identifica la marca promocionada en la fuente si está presente; déjala como desconocida si no lo está.',
  'Multiple brand candidates': 'Varias marcas candidatas',
  'Several extracted names are possible candidates. Check which, if any, is actually being promoted.': 'Varios nombres extraídos son posibles candidatos. Revisa cuál, si corresponde, se está promocionando.',
  'No saved evidence excerpt': 'No hay un fragmento de evidencia guardado',
  'No rule excerpt or JEV context excerpt is available in this result. Open the post before deciding.': 'Este resultado no tiene un fragmento de regla ni de contexto de JEV. Abre la publicación antes de decidir.',
  'Indirect evidence only': 'Solo hay evidencia indirecta',
  'The saved rules do not include explicit disclosure, partnership metadata or affiliate evidence. Inspect the commercial context.': 'Las reglas guardadas no incluyen una declaración explícita, metadatos de colaboración ni evidencia de afiliación. Revisa el contexto comercial.',
  'No additional issues surfaced in the loaded evidence.': 'No se encontraron problemas adicionales en la evidencia cargada.',
  'SAVED RULE EVIDENCE': 'EVIDENCIA GUARDADA DE REGLAS',
  'Signal': 'Señal', 'source unspecified': 'fuente sin especificar', 'Excerpt unavailable': 'Fragmento no disponible',
  'No saved rule evidence.': 'No hay evidencia de reglas guardada.',
  'EXTRACTED BRAND CANDIDATES': 'MARCAS CANDIDATAS EXTRAÍDAS',
  'SAVED JEV ASSESSMENT': 'EVALUACIÓN JEV GUARDADA',
  'Relationship reading': 'Lectura de la relación', 'Recommendation': 'Recomendación',
  'Rules at JEV review': 'Reglas al momento de la revisión JEV', 'Unavailable': 'No disponible',
  'Guidance': 'Orientación', 'Reviewed excerpt': 'Fragmento revisado', 'stored context': 'contexto guardado',
  'OBSERVED LINKS': 'ENLACES OBSERVADOS', 'Observed CTA keyword': 'Palabra clave de llamada a la acción observada',
  'Observed promo code': 'Código promocional observado', 'RELATED LOADED POSTS': 'PUBLICACIONES RELACIONADAS CARGADAS',
  'Same topic stack': 'Mismo grupo temático', 'Same brand and product': 'Misma marca y producto', 'Same brand': 'Misma marca',
  'Scope: this brief uses loaded evidence and saved assessments. Related posts are comparisons, not proof of a shared campaign. Promotion signals do not verify payment.': 'Alcance: este brief utiliza evidencia cargada y evaluaciones guardadas. Las publicaciones relacionadas son comparaciones, no pruebas de una campaña compartida. Las señales de promoción no verifican un pago.',
  'Disclosed promotion': 'Promoción declarada', 'Likely promotion': 'Promoción probable',
  'Needs review': 'Necesita revisión', 'Not a promotion': 'No es una promoción',
  'Sponsored or paid-placement language': 'Lenguaje de patrocinio o colocación pagada',
  'Affiliate or referral offer': 'Oferta de afiliación o referidos',
  'Gifted product or brand relationship': 'Producto regalado o relación con la marca',
  'Own product or service': 'Producto o servicio propio', 'Organic recommendation': 'Recomendación orgánica',
  'Editorial mention without an offer': 'Mención editorial sin una oferta', 'Unclear relationship': 'Relación poco clara',
  'Caption': 'Texto de la publicación', 'First comment': 'Primer comentario', 'Post metadata': 'Metadatos de la publicación',
  'Partnership metadata': 'Metadatos de colaboración', 'Image alt text': 'Texto alternativo de la imagen',
  'Transcript': 'Transcripción', 'Cover text': 'Texto de portada', 'Requested JEV review': 'Revisión JEV solicitada',
  'JEV discovery': 'Descubrimiento JEV', 'Hashtag': 'Hashtag', 'Mention': 'Mención', 'URL': 'URL',
  'Disclosure language': 'Declaración comercial', 'Brand relationship': 'Relación con la marca',
  'Call to action': 'Llamada a la acción', 'Commercial language': 'Lenguaje comercial',
  'Hashtag signal': 'Señal de hashtag', 'Related-post support': 'Apoyo de publicaciones relacionadas',
  'Possible missed promotion': 'Posible promoción no detectada', 'Conflicting evidence': 'Evidencia contradictoria',
  'Needs human review': 'Necesita revisión humana', 'No promotion signal found': 'No se encontraron señales de promoción',
  'Assessment available': 'Evaluación disponible',
});
